In [2]:
import numpy as np
import pandas as pd 
import seaborn as sns

In [3]:
#reading file
ds = pd.read_csv('laptop_price.csv', encoding='latin1')

In [7]:
ds

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

In [5]:
ds.describe()

         laptop_ID       Inches  Price_euros
count  1303.000000  1303.000000  1303.000000
mean    660.155794    15.017191  1123.686992
std     381.172104     1.426304   699.009043
min       1.000000    10.100000   174.000000
25%     331.500000    14.000000   599.000000
50%     659.000000    15.600000   977.000000
75%     990.500000    15.600000  1487.880000
max    1320.000000    18.400000  6099.000000

In [6]:
ds.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [11]:
ds.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [14]:
#cleaning RAM
ds['Ram']=ds['Ram'].str.replace('GB','').astype(int)

In [16]:
#cleaning Weight
ds['Weight']=ds['Weight'].str.replace('kg','').astype(float)

In [23]:
ds['Cpu_Brand'] = ds['Cpu'].apply(lambda x: x.split()[0]

In [25]:
#droping cpu column because theres cpu_brand (cleaned) column
ds.drop('Cpu',axis=1,inplace=True)

In [26]:
ds

,Company,TypeName,Inches,ScreenResolution,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Brand
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel
1,Apple,Ultrabook,13.3,1440x900,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,898.94,Intel
2,HP,Notebook,15.6,Full HD 1920x1080,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,575.00,Intel
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,638.00,Intel
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,1499.00,Intel
1300,Lenovo,Notebook,14.0,1366x768,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,229.00,Intel
1301,HP,Notebook,15.6,1366x768,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,764.00,Intel
1302,Asus,Notebook,15.6,1366x768,4,500GB HDD,Intel HD Graphics,Windows 10,2.20,369.00,Intel

In [28]:
ds['Gpu'] = ds['Gpu'].apply(lambda x: x.split()[0])

In [29]:
ds

,Company,TypeName,Inches,ScreenResolution,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Brand
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8,128GB SSD,Intel,macOS,1.37,1339.69,Intel
1,Apple,Ultrabook,13.3,1440x900,8,128GB Flash Storage,Intel,macOS,1.34,898.94,Intel
2,HP,Notebook,15.6,Full HD 1920x1080,8,256GB SSD,Intel,No OS,1.86,575.00,Intel
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16,512GB SSD,AMD,macOS,1.83,2537.45,Intel
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8,256GB SSD,Intel,macOS,1.37,1803.60,Intel
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4,128GB SSD,Intel,Windows 10,1.80,638.00,Intel
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16,512GB SSD,Intel,Windows 10,1.30,1499.00,Intel
1300,Lenovo,Notebook,14.0,1366x768,2,64GB Flash Storage,Intel,Windows 10,1.50,229.00,Intel
1301,HP,Notebook,15.6,1366x768,6,1TB HDD,AMD,Windows 10,2.19,764.00,Intel
1302,Asus,Notebook,15.6,1366x768,4,500GB HDD,Intel,Windows 10,2.20,369.00,Intel

In [33]:
# Assistant
def get_hdd(memory):
    if 'HDD' in memory:
        if 'TB' in memory:
            # Extract the number before TB
            tb_value = memory.split('TB')[0].strip()
            if tb_value.replace('.', '', 1).isdigit():  # Handle decimal points
                return float(tb_value) * 1000  # Convert TB to GB equivalent
        elif 'GB' in memory:
            # Extract the number before GB
            gb_value = memory.split('GB')[0].strip()
            if gb_value.replace('.', '', 1).isdigit():  # Handle decimal points
                return float(gb_value)
        return 0  # Default if format is unrecognized
    return 0

def get_ssd(memory):
    if 'SSD' in memory:
        if 'TB' in memory:
            # Extract the number before TB
            tb_value = memory.split('TB')[0].strip()
            if tb_value.replace('.', '', 1).isdigit():  # Handle decimal points
                return float(tb_value) * 1000  # Convert TB to GB equivalent
        elif 'GB' in memory:
            # Extract the number before GB
            gb_value = memory.split('GB')[0].strip()
            if gb_value.replace('.', '', 1).isdigit():  # Handle decimal points
                return float(gb_value)
        return 0  # Default if format is unrecognized
    return 0

ds['HDD'] = ds['Memory'].apply(get_hdd)
ds['SSD'] = ds['Memory'].apply(get_ssd)

# Drop original memory column if no longer needed
ds.drop('Memory', axis=1, inplace=True)

In [34]:
ds

,Company,TypeName,Inches,ScreenResolution,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Brand,HDD,SSD
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8,Intel,macOS,1.37,1339.69,Intel,0.0,128.0
1,Apple,Ultrabook,13.3,1440x900,8,Intel,macOS,1.34,898.94,Intel,0.0,0.0
2,HP,Notebook,15.6,Full HD 1920x1080,8,Intel,No OS,1.86,575.00,Intel,0.0,256.0
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16,AMD,macOS,1.83,2537.45,Intel,0.0,512.0
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8,Intel,macOS,1.37,1803.60,Intel,0.0,256.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4,Intel,Windows 10,1.80,638.00,Intel,0.0,128.0
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16,Intel,Windows 10,1.30,1499.00,Intel,0.0,512.0
1300,Lenovo,Notebook,14.0,1366x768,2,Intel,Windows 10,1.50,229.00,Intel,0.0,0.0
1301,HP,Notebook,15.6,1366x768,6,AMD,Windows 10,2.19,764.00,Intel,1000.0,0.0
1302,Asus,Notebook,15.6,1366x768,4,Intel,Windows 10,2.20,369.00,Intel,500.0,0.0

In [37]:
ds['OpSys'] = ds['OpSys'].replace({
    'Windows 10': 'Windows',
    'Windows 7': 'Windows',
    'Windows 8': 'Windows',
    'macOS': 'Mac',
    'Mac OS X': 'Mac',
    'Chrome OS': 'Others',
    'Linux': 'Others',
    'No OS': 'Others'
})

In [39]:
from sklearn.preprocessing import LabelEncoder

label_enc_cols = ['Company', 'TypeName', 'Cpu_Brand', 'Gpu', 'OpSys']
le = LabelEncoder()

for col in label_enc_cols:
    ds[col] = le.fit_transform(ds[col])

In [40]:
ds

,Company,TypeName,Inches,ScreenResolution,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Brand,HDD,SSD
0,1,4,13.3,IPS Panel Retina Display 2560x1600,8,2,1,1.37,1339.69,1,0.0,128.0
1,1,4,13.3,1440x900,8,2,1,1.34,898.94,1,0.0,0.0
2,7,3,15.6,Full HD 1920x1080,8,2,2,1.86,575.00,1,0.0,256.0
3,1,4,15.4,IPS Panel Retina Display 2880x1800,16,0,1,1.83,2537.45,1,0.0,512.0
4,1,4,13.3,IPS Panel Retina Display 2560x1600,8,2,1,1.37,1803.60,1,0.0,256.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,10,0,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4,2,3,1.80,638.00,1,0.0,128.0
1299,10,0,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16,2,3,1.30,1499.00,1,0.0,512.0
1300,10,3,14.0,1366x768,2,2,3,1.50,229.00,1,0.0,0.0
1301,7,3,15.6,1366x768,6,0,3,2.19,764.00,1,1000.0,0.0
1302,2,3,15.6,1366x768,4,2,3,2.20,369.00,1,500.0,0.0

In [42]:
ds=ds[ds['Ram']>=8]

In [43]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 865 entries, 0 to 1299
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           865 non-null    int64
 1   TypeName          865 non-null    int64
 2   Inches            865 non-null    float64
 3   ScreenResolution  865 non-null    object
 4   Ram               865 non-null    int32
 5   Gpu               865 non-null    int32
 6   OpSys             865 non-null    int32
 7   Weight            865 non-null    float64
 8   Price_euros       865 non-null    float64
 9   Cpu_Brand         865 non-null    int64
 10  HDD               865 non-null    float64
 11  SSD               865 non-null    float64
dtypes: float64(5), int32(3), int64(3), object(1)
memory usage: 77.7+ KB

In [44]:
ds

,Company,TypeName,Inches,ScreenResolution,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Brand,HDD,SSD
0,1,4,13.3,IPS Panel Retina Display 2560x1600,8,2,1,1.37,1339.69,1,0.0,128.0
1,1,4,13.3,1440x900,8,2,1,1.34,898.94,1,0.0,0.0
2,7,3,15.6,Full HD 1920x1080,8,2,2,1.86,575.00,1,0.0,256.0
3,1,4,15.4,IPS Panel Retina Display 2880x1800,16,0,1,1.83,2537.45,1,0.0,512.0
4,1,4,13.3,IPS Panel Retina Display 2560x1600,8,2,1,1.37,1803.60,1,0.0,256.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1285,10,0,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16,2,3,1.30,1499.00,1,0.0,512.0
1289,2,4,13.3,IPS Panel Full HD 1920x1080,8,2,3,1.20,729.00,1,0.0,512.0
1293,10,3,15.6,IPS Panel Full HD 1920x1080,8,3,3,2.60,899.00,1,1000.0,0.0
1295,4,3,15.6,1366x768,8,0,2,2.30,805.99,1,1000.0,0.0
1299,10,0,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16,2,3,1.30,1499.00,1,0.0,512.0

In [45]:
# Extract Touchscreen
ds['Touchscreen'] = ds['ScreenResolution'].apply(lambda x: 1 if 'Touchscreen' in x else 0)

# Extract IPS Panel
ds['IPS'] = ds['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)

# Extract X and Y resolution
resolution = ds['ScreenResolution'].str.extract(r'(\d+)x(\d+)')
ds['X_res'] = resolution[0].astype('int')
ds['Y_res'] = resolution[1].astype('int')

# Calculate PPI (Pixels Per Inch)
ds['PPI'] = ((ds['X_res']**2 + ds['Y_res']**2) ** 0.5) / ds['Inches']

# Drop original ScreenResolution
ds.drop('ScreenResolution', axis=1, inplace=True)

In [46]:
ds

,Company,TypeName,Inches,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Brand,HDD,SSD,Touchscreen,IPS,X_res,Y_res,PPI
0,1,4,13.3,8,2,1,1.37,1339.69,1,0.0,128.0,0,1,2560,1600,226.983005
1,1,4,13.3,8,2,1,1.34,898.94,1,0.0,0.0,0,0,1440,900,127.677940
2,7,3,15.6,8,2,2,1.86,575.00,1,0.0,256.0,0,0,1920,1080,141.211998
3,1,4,15.4,16,0,1,1.83,2537.45,1,0.0,512.0,0,1,2880,1800,220.534624
4,1,4,13.3,8,2,1,1.37,1803.60,1,0.0,256.0,0,1,2560,1600,226.983005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1285,10,0,13.3,16,2,3,1.30,1499.00,1,0.0,512.0,1,1,3200,1800,276.053530
1289,2,4,13.3,8,2,3,1.20,729.00,1,0.0,512.0,0,1,1920,1080,165.632118
1293,10,3,15.6,8,3,3,2.60,899.00,1,1000.0,0.0,0,1,1920,1080,141.211998
1295,4,3,15.6,8,0,2,2.30,805.99,1,1000.0,0.0,0,0,1366,768,100.454670
1299,10,0,13.3,16,2,3,1.30,1499.00,1,0.0,512.0,1,1,3200,1800,276.053530

In [47]:
ds.to_csv("myproject_data.csv")